<template>
  <div class="overflow-hidden bg-white py-24 sm:py-32">
    <div class="mx-auto max-w-7xl md:px-6 lg:px-8">
      <div class="grid grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:grid-cols-2 lg:items-start">
        <div class="px-6 lg:px-0 lg:pr-4 lg:pt-4">
          <div class="mx-auto max-w-2xl lg:mx-0 lg:max-w-lg">
            <h2 class="text-base font-semibold leading-7 text-indigo-600">Try It Now!</h2>
            <p class="mt-6 text-lg leading-8 text-gray-600">We currently offer two products for trial</p>
            <p class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Virtual Agent</p>
            <p class="mt-6 text-lg leading-8 text-gray-600"> 
We believe that our Virtual Agent can out-perform your digital customer care team for most use cases and we’d like to prove it.  We’ll create a bot for you based on your enterprise training material (or web site).  This process takes about a day and we’d love to make an Enegel.ai Virtual Agent for your business.
Please provide your contact information below and a representative will contact you to discuss your use case and collect training material for your prototype bot.
Once you provide training material we’ll create a prototype bot in the testing area of our web site and you can try Enegel.ai Virtual Agent for yourself.</p>
            <p></p>
            <p class="mt-2 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Conversational Intelligence</p>
            <p class="mt-6 text-lg leading-8 text-gray-600">
We’re confident Enegel can produce the highest quality evaluation of agent performance and we’d like to show you with a complimentary analysis. Compare Enegel’s CX Assurance report to the reports produced by your quality assurance process and tell us how we did! </p>
            <p class="mt-6 text-lg leading-8 font-semibold text-gray-600">
              Upload a customer service transcript (or audio recording) and Enegel will email you a free agent performance evaluation generated by our AI platform.</p>
            <div id="hubspot-tryit-form" class="mt-4"></div>
          </div>
        </div>
        <div class="sm:px-6 lg:px-0">
          <div class="relative isolate overflow-hidden bg-indigo-500 px-6 pt-8 sm:mx-auto sm:max-w-2xl sm:rounded-3xl sm:pl-16 sm:pr-0 sm:pt-16 lg:mx-0 lg:max-w-none">
            <div class="absolute -inset-y-px -left-3 -z-10 w-full origin-bottom-left skew-x-[-30deg] bg-indigo-100 opacity-20 ring-1 ring-inset ring-white" aria-hidden="true" />
            <div class="mx-auto max-w-2xl sm:mx-0 sm:max-w-none">
              <img src="/img/report.png" alt="Product screenshot" class="w-[33rem] max-w-none rounded-tl-xl bg-gray-800 ring-1 ring-white/10" />
            </div>
            <div class="pointer-events-none absolute inset-0 ring-1 ring-inset ring-black/10 sm:rounded-3xl" aria-hidden="true" />
          </div>
        </div>
      </div>
      <div class="mt-10 pb-5">
        <h3 class="text-base font-semibold leading-6 text-gray-900">The analysis will be produced by Enegel’s proprietary scoring for the following agent performance metrics</h3>
      </div>
      <div class="mt-10 grid grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 md:grid-cols-2 lg:grid-cols-3 lg:items-start">
          <div v-for="feature in features" :key="feature.name" class="relative pl-9 flex items-start">
            <dt class="inline font-semibold text-gray-900">
              <component :is="feature.icon" class="absolute left-1 top-1 h-10 w-10 text-orange-600/70" aria-hidden="true" />
            </dt>
            <dd class="inline mt-2 ml-4">
              <p class="font-semibold text-xl text-gray-900 mb-2">{{ feature.name }}</p>
              {{ feature.description }}
            </dd>
          </div>
      </div>
      </div>
    <loading v-model:active="isLoading"
             :can-cancel="false"
             :is-full-page="true"/>
  </div>
</template>

<script setup>
import { CloudArrowUpIcon, LockClosedIcon, ShieldCheckIcon, CheckCircleIcon } from '@heroicons/vue/20/solid'
import {onMounted, ref} from "vue";
import Loading from 'vue-loading-overlay';
import 'vue-loading-overlay/dist/css/index.css';

const isLoading = ref(false);

const features = [
  {
    name: 'Personalization and context',
    description:
      "Analyze how well the Agent can personalize the conversation and understand the context of the customer's query.",
    icon: CheckCircleIcon,
  },
  {
    name: 'Language and tone',
    description: 'Analyze the language and tone used by the Agent in responses to the customer. Ensure that Agent uses clear and appropriate language and a friendly and helpful tone.',
    icon: CheckCircleIcon,
  },
  {
    name: 'Flow and logic of conversation',
    description:
      "Evaluate the flow and logic of the conversation between the Customer and the Agent. Ensure that the Agent can guide the Customer through a logical sequence of questions and answers.",
    icon: CheckCircleIcon,
  },
  {
    name: 'Two-way conversation',
    description:
      "Ensure that Agent creates and build rapport with the customer. Determine if Agent was able to have a a two-way conversation with Customer outside the sale interaction.",
    icon: CheckCircleIcon,
  },
  {
    name: 'Customer satisfaction',
    description:
      "Evaluate the Customer's overall satisfaction with the customer service. Determine if service provided is meeting the customer's needs.",
    icon: CheckCircleIcon,
  },
  {
    name: 'Accuracy of responses',
    description:
      "Ensure that the Agent provides accurate information and instructions to the customer. Check if Agent can correctly answer the customer's questions or concerns.",
    icon: CheckCircleIcon,
  },
  {
    name: 'Net Promoter Score',
    description:
      "How likely is it that Customer would recommend Customer Service to a friend or colleague?",
    icon: CheckCircleIcon,
  },
  {
    name: 'Sound like an Expert',
    description:
      "Ensure that Agent was able to provide accurate and complete information to the customer. Ensure that Agent is CONFIDENT when assisting the customer.",
    icon: CheckCircleIcon,
  }
]

const formCSS = '.hs-form input[type="text"] {\n' +
    '  background: #FFF222 !important;\n' +
    '}\n' +
    '\n' +
    '.hs-button-reset,\n' +
    '.hs-form .hs-button {\n' +
    '  background: #FFF222;\n' +
    '  border: none;\n' +
    '  font-family: Helvetica, Arial, sans-serif;\n' +
    '  line-height: 1;\n' +
    '  margin: 0;\n' +
    '  outline: 0;\n' +
    '  padding: 0;\n' +
    '\n' +
    '}';

onMounted(()=>{
  try {
    hbspt.forms.create({
      region: "na1",
      portalId: "39953401",
      formId: "e31f8b36-cf3a-45de-9081-c472e3852e3d",
      target: '#hubspot-tryit-form',
      onFormSubmit: function($form){
        console.log(`onFormSubmit`)
        isLoading.value = true;
      },
      onFormSubmitted: function($form){
        console.log(`onFormSubmitted`)
        isLoading.value = false;
      }
    });
  }catch (e) {
    console.log(`Hubspot form failed`);
  }

});

</script>


